[global]
dataFrameSerialization = "legacy"

[server]
port = 8501
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#1f77b4"
backgroundColor = "#000000ff"
secondaryBackgroundColor = "#24385fff"
textColor = "#ffffffff"
font = "sans serif"
